// <auto-generated />
namespace MaryamRahimiFard.Infratructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class makeDurationAndSessionsNumberNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(makeDurationAndSessionsNumberNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "202107311322493_makeDurationAndSessionsNumberNullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
